### Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np
list1=[1,2,3,4,5,6,7,8,9,10]
list2=[11,12,13,14,15,16,17,18,19,20]
matrix1=np.array(list1)
matrix2=np.array(list2)
a=matrix1.reshape(5,2)
b=matrix2.reshape(5,2)
print(a+b)

[[12 14]
 [16 18]
 [20 22]
 [24 26]
 [28 30]]


### Write a Python Program to Multiply Two Matrices?

In [3]:

import numpy as np
m1=[]
n=int(input("enter  10 for the first matrix  10 elements"))
for i in range(0,n):
    p=int(input())
    m1.append(p)
m2=[]
m=int(input("enter  10 for the second matrix  10 elements"))
for i in range(0,m):
    q=int(input())
    m2.append(q)
    

matrix1=np.array(m1)
matrix2=np.array(m2)
a=matrix1.reshape(5,2)
b=matrix2.reshape(5,2)
print(a*b)

enter  10 for the first matrix  10 elements10
5
7
8
9
4
5
6
5
4
5
enter  10 for the second matrix  10 elements10
1
2
3
4
5
6
7
8
9
4
[[ 5 14]
 [24 36]
 [20 30]
 [42 40]
 [36 20]]


### Write a Python Program to Transpose a Matrix?

In [19]:
# creating a martrix
import numpy as np
a=np.array([ [1,2,3],[4,5,6],[7,8,9] ])
print(a)
a.transpose()


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [14]:
# generate a matrix
!pip install numpy
import numpy as np
b=np.arange(1,10)
b.reshape(3,3)
print(b)

[1 2 3 4 5 6 7 8 9]


In [16]:
b.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Write a Python Program to Sort Words in Alphabetic Order?

In [38]:
word=input("enter the word   ")
l=list(word.split())
print(l)
l.sort()
for i in l:
  print(i)

enter the word   this is ineuron with data science Course
['this', 'is', 'ineuron', 'with', 'data', 'science', 'Course']
Course
data
ineuron
is
science
this
with


### Write a Python Program to Remove Punctuation From a String?

In [45]:
punc='.!@#$%{}^&*():[]<>>?;\/""'
p=""
s=input("enter the string   ")
for i in s:
    if i not in punc:
        p=p+i
print(p)

enter the string   $%ineuron*&
ineuron
